name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: "Lint and test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo apt install -y git curl
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/refs/heads/master/nvm.sh | bash
          export NVM_DIR="$HOME/.nvm" \
            && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
            && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
            && nvm install 20 \
            && sudo ln -s $(which node) /usr/bin/node \
            && sudo ln -s $(which npm) /usr/bin/npm

      - name: Install commitlint
        run: |
          npm install @commitlint/config-conventional

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
